# Generated by Django 3.0.4 on 2020-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='author',
            field=models.CharField(default='Jyunmau Chan', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogspost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
